# Check out Dependabot at: https://github.com/dependabot

version: 2
updates:
- package-ecosystem: gomod
  directory: /
  open-pull-requests-limit: 1
  schedule:
    interval: daily
    time: "04:00"
  labels:
  - dependencies
- package-ecosystem: github-actions
  directory: /
  open-pull-requests-limit: 1
  schedule:
    interval: daily
    time: "04:00"
  labels:
  - ci/cd
  - dependencies
- package-ecosystem: npm
  directory: /web
  open-pull-requests-limit: 1
  schedule:
    interval: daily
    time: "04:00"
  labels:
  - dependencies
