name: ghasum
description: Verify checksums of actions

inputs:
  workflow:
    description: The workflow to verify.
    required: false
    default: ${{ job.workflow_ref }}

runs:
  using: node24
  main: main.js
  pre: pre.js
