name: Renovate
on:
  pull_request:
    branches:
    - renovate/**
  push:
    branches:
    - renovate/**

permissions: read-all

jobs:
  gha-release:
    name: GitHub Actions Release Immutability
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request' && github.actor == 'renovate[bot]'
    permissions:
      pull-requests: write # To comment on a Pull Request
    steps:
    - name: Parse
      id: parse
      shell: bash
      env:
        BODY: ${{ github.event.pull_request.body }}
      run: |
        ROW=$(echo "${BODY}" | grep -m1 '^| .* | action |') || true
        REPO=$(echo "${ROW}" | cut -d'|' -f2 | sed -nE 's/.*\[([^]]+)\].*/\1/p')
        OLD=$(echo "${ROW}" | cut -d'|' -f5 | awk -F'`' '{print $2}')
        NEW=$(echo "${ROW}" | cut -d'|' -f5 | awk -F'`' '{print $4}')

        {
          echo "repo=$REPO"
          echo "new=$NEW"
          echo "old=$OLD"
        } >>"$GITHUB_OUTPUT"
    - name: Check
      if: steps.parse.outputs.repo != ''
      id: check
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        NEW: ${{ steps.parse.outputs.new }}
        NUMBER: ${{ github.event.pull_request.number }}
        OLD: ${{ steps.parse.outputs.old }}
        THAT_REPO: ${{ steps.parse.outputs.repo }}
        THIS_REPO: ${{ github.repository }}
      run: |
        set -euo pipefail

        WAS_IMMUTABLE=$(gh release view "${OLD}" --repo "${THAT_REPO}" --json isImmutable | jq .isImmutable)
        IS_IMMUTABLE=$(gh release view "${NEW}" --repo "${THAT_REPO}" --json isImmutable | jq .isImmutable)

        echo "::debug::was ${WAS_IMMUTABLE}; is ${IS_IMMUTABLE}"
        case "${WAS_IMMUTABLE};${IS_IMMUTABLE}" in
        'true;true')
          COMMENT=""
          ;;
        'false;false')
          COMMENT="${OLD} was not an immutable release and ${NEW} still is not. :neutral_face:"
          ;;
        'true;false')
          COMMENT="${OLD} was an immutable release but ${NEW} is not. :cry:"
          ;;
        'false;true')
          COMMENT="${OLD} was not an immutable release but ${NEW} is! :smile:"
          ;;
        esac

        exists=$(gh pr view "${NUMBER}" --repo "${THIS_REPO}" --json comments | jq --raw-output --arg comment "${COMMENT}" 'any(.comments[].body; . == $comment)')
        if [[ ${exists} == 'true' ]]; then
          echo '::debug::comment exists, not commenting again'
          SKIP='true'
        else
          echo '::debug::comment does not yet exists'
          SKIP='false'
        fi

        echo "comment=${COMMENT}" >>"$GITHUB_OUTPUT"
        echo "skip=${SKIP}" >>"$GITHUB_OUTPUT"
    - name: Comment
      if: steps.parse.outputs.repo != '' && steps.check.outputs.comment != '' && steps.check.outputs.skip == 'false'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        COMMENT: ${{ steps.check.outputs.comment }}
        NUMBER: ${{ github.event.pull_request.number }}
        THIS_REPO: ${{ github.repository }}
      run: |
        gh pr comment "${NUMBER}" --repo "${THIS_REPO}" --body "${COMMENT}"
  ghasum:
    name: Update gha.sum
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.actor == 'renovate[bot]'
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 2 # required for --amend
        persist-credentials: false
    - name: Install Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - name: Create automation token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: automation-token
      with:
        client-id: ${{ secrets.AUTOMATION_APP_ID }}
        permission-contents: write # To push a commit
        permission-workflows: write # To push gha.sum
        private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
    - name: Update gha.sum
      run: go run github.com/chains-project/ghasum/cmd/ghasum update
    - name: Commit gha.sum
      env:
        BRANCH: ${{ github.ref_name }}
        GH_TOKEN: ${{ steps.automation-token.outputs.token }}
        REPOSITORY: ${{ github.repository }}
      run: |
        if [ -z "$(git status --porcelain)" ]; then
          echo 'Already up-to-date'
          exit 0
        fi

        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        git add '.github/workflows/gha.sum'
        git commit --amend --no-edit --trailer 'Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

        git remote set-url 'origin' "https://x-access-token:${GH_TOKEN}@github.com/${REPOSITORY}"
        git push --force 'origin' "HEAD:${BRANCH}"
